#define VM_USERLO     0x40000000
#define VM_USERHI     0xF0000000
#define VM_USERLO_PDE (VM_USERLO / PDIRSIZE)
#define VM_USERHI_PDE (VM_USERHI / PDIRSIZE)
//???
#define SHARED_PAGE_VADDR   VM_USERLO + (32 * PAGESIZE)

